#!/usr/bin/python3
# Made executable with chmod -x domletters.py
"""
    Zach Santangelo
    CS461P HW1
"""
from sys import stdin
import os.path

def is_valid_word(word):
    for letter in word:
        print(word) 
        if(letter.isalpha() == False):
            return False
       
    return True


def count_dom_letters(sentence):
    alphabet=[]
    for i in range(97,123):
        alphabet.append(chr(i))
    #print(alphabet)

    dom_letters_total = 0

    for word in sentence:
                #print("\n" + word + "\n")
        dom_letter_count_in_word = 0
        if(is_valid_word(word)):
            for char in alphabet:     
                char_counts = 0        #for each character in the alphabetbet, check how many times it appears. 
                for letter in word:
                    if(letter.lower() == char):
                        char_counts += 1
                    if(char_counts > dom_letter_count_in_word):
                        dom_letter_count_in_word = char_counts
        
        dom_letters_total += dom_letter_count_in_word

    print("Total dom letters: " + str(dom_letters_total))
        


if __name__ == "__main__": 
    
    sentence = ''
    for line in stdin:
        line = line.strip('\n')
        sentence += line + ' '


    sentence = sentence.strip(' ')
    sentence = sentence.split(' ')



    count_dom_letters(sentence)